version: '3.8'

services:
  apriltag_detector:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apriltag_ros2
    network_mode: host
    privileged: true
    environment:
      - DISPLAY=${DISPLAY:-:0}
      - ROS_DOMAIN_ID=0
    volumes:
      - ./src:/ros2_ws/src
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/.Xauthority:/root/.Xauthority:rw
    ports:
      - "5555:5555"  # For webcam frame streaming
    stdin_open: true
    tty: true
    command: bash -c "source /opt/ros/jazzy/setup.bash && colcon build --symlink-install && source install/setup.bash && ros2 launch apriltag_detector apriltag_demo.launch.py"
