services:
  apriltag_detector:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apriltag_ros2
    # Note: network_mode: host doesn't work on Mac Docker Desktop
    environment:
      - DISPLAY=${DISPLAY:-:0}
      - ROS_DOMAIN_ID=0
    volumes:
      - ./src:/ros2_ws/src
    ports:
      - "5555:5555"  # For webcam frame streaming from Mac host
    stdin_open: true
    tty: true
    command: bash -c "source /opt/ros/jazzy/setup.bash && colcon build --symlink-install && source install/setup.bash && ros2 launch apriltag_detector apriltag_demo.launch.py"
